### ISSUE TITLE
コメント行をインデント対象にしていないのはなぜでしょうか。

### ISSUE THREAD

**Issue by coeracanth** [lunany188/vscode-eraIndent#7]
ソースの該当箇所にコメントありますが、
コメント行をインデント対象にしていないのはなぜでしょうか。
https://github.com/lunany188/vscode-eraIndent/blob/73fd347086b4e90b3470dcb6c5948f1d7c7f3d69/src/indenter.ts#L341-L343

vscodeで開発する場合、コードの折りたたみ(fold)の範囲がインデント依存なので、
コメント行もインデント対象になっているほうが折りたたみ機能を使う場合見やすいかなと思いました。

慣例的に分岐条件の直前の行にコメントがあることが多く、
コメント対象の行とコメント行のインデントがずれてわかりにくくなるとの判断でしょうか。

e.g.
```erb
;xxxの場合
IF COND("xxx")
	PRINTFORML xxx
;yyyの場合    ←こういうの
ELSEIF COND("yyy")
	PRINTFORML yyy
;その他    ←こういうの
ELSE
	PRINTFORML zzz
ENDIF
```
↓
```erb
;xxxの場合
IF COND("xxx")
	PRINTFORML xxx
	;yyyの場合    ←こういうの
ELSEIF COND("yyy")
	PRINTFORML yyy
	;その他    ←こういうの
ELSE
	PRINTFORML zzz
ENDIF
```

**Comment by lunany188** [comment]
おおよそその事例が原因になりますが少しその例に類似した事例と合わせ一貫したインデントルールが作成できないことです
その様に次の行に対してコメントを入れる場合もあり得ますが
```
IF COND("xxx")
	PRINTFORML xxx
	;DEBUGPRINT hoge ←こういうの
ELSEIF COND("yyy")
	PRINTFORML yyy
        ;○/○ 更新        ←こういうの　　　
        ;PRINTFORML aaa  ←こういうの
ELSE
	PRINTFORML zzz
ENDIF
```
のように前の行とインデントが一致しているべき事例が発生することもあり得ます。
そのためコメントに対して文脈に即したインデントルールを作成することの困難さを感じたためコメントについては利用者が直接インデントを取り扱う方がより適切にインデントできるだろうと考えました。
あと個人的な話をするとこれを実装したさいかなり勢いで実装したため複雑な処理を作ることを嫌ったというのもあります。そのようなルールを(仮に定めたとして)実装するためには(連続したコメント行などもあり得るため)不特定多数の行の先読みが必要になります。実装が複雑で面倒になるのと先のルールが一貫して定められないことと合わせ対象としませんでした
